// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5nWdNb-zabT3j41PNcqSbWTUZA-BwN_A',
    appId: '1:1058298655225:web:561fc0af7264b486634d28',
    messagingSenderId: '1058298655225',
    projectId: 'educonnect-pro-248ea',
    authDomain: 'educonnect-pro-248ea.firebaseapp.com',
    storageBucket: 'educonnect-pro-248ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR3JwiNCGup7cLzoUmQZD8TOao6-AinHQ',
    appId: '1:1058298655225:android:11da0ea940ac0564634d28',
    messagingSenderId: '1058298655225',
    projectId: 'educonnect-pro-248ea',
    storageBucket: 'educonnect-pro-248ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCphZaSDwzGm3iBSGVCaP8F6-oKGd7elfU',
    appId: '1:1058298655225:ios:a7d0a98710b3a705634d28',
    messagingSenderId: '1058298655225',
    projectId: 'educonnect-pro-248ea',
    storageBucket: 'educonnect-pro-248ea.firebasestorage.app',
    iosBundleId: 'com.example.eduConnectPro',
  );
}
